# fly.toml app configuration file generated for bklt-cache on 2023-10-18T14:54:31-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bklt-cache"
primary_region = "ewr"

[build]
  dockerfile = "Dockerfile"

[deploy]
  strategy = "rolling"
